namespace JSO.Domain;

public sealed class Club { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = "Jeunesse Sportive de Oudhref"; public string ShortName { get; set; } = "JSO"; public string Country { get; set; } = "Tunisie"; public string City { get; set; } = "Oudhref"; public string? Description { get; set; } public string? LogoUrl { get; set; } }
public sealed class Season { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public bool IsActive { get; set; } }
public sealed class Competition { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public string? Country { get; set; } }
public sealed class Team { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public string Category { get; set; } = null!; public bool IsActive { get; set; } = true; }
public sealed class Player { public Guid Id { get; set; } = Guid.NewGuid(); public Guid TeamId { get; set; } public string FirstName { get; set; } = null!; public string LastName { get; set; } = null!; public int? ShirtNumber { get; set; } public string? Position { get; set; } public string? PhotoUrl { get; set; } public bool IsActive { get; set; } = true; }
public sealed class StaffMember { public Guid Id { get; set; } = Guid.NewGuid(); public Guid TeamId { get; set; } public string Name { get; set; } = null!; public string Role { get; set; } = null!; public string? PhotoUrl { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Match { public Guid Id { get; set; } = Guid.NewGuid(); public Guid SeasonId { get; set; } public Guid CompetitionId { get; set; } public Guid TeamId { get; set; } public string OpponentName { get; set; } = null!; public DateTimeOffset KickoffAt { get; set; } public string? Venue { get; set; } public bool IsHome { get; set; } public int? HomeScore { get; set; } public int? AwayScore { get; set; } public string Status { get; set; } = "Scheduled"; public bool IsPublished { get; set; } }
public sealed class MatchEvent { public Guid Id { get; set; } = Guid.NewGuid(); public Guid MatchId { get; set; } public int Minute { get; set; } public string Type { get; set; } = null!; public string? PlayerName { get; set; } public string? Notes { get; set; } }
public sealed class Article { public Guid Id { get; set; } = Guid.NewGuid(); public string Title { get; set; } = null!; public string Slug { get; set; } = null!; public string Excerpt { get; set; } = null!; public string Body { get; set; } = null!; public string Status { get; set; } = "Draft"; public DateTimeOffset? PublishedAt { get; set; } public string? CoverImageUrl { get; set; } }
public sealed class Sponsor { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public string? LogoUrl { get; set; } public string? WebsiteUrl { get; set; } public string Tier { get; set; } = "Partner"; public string Placement { get; set; } = "Footer"; public DateTimeOffset? StartDate { get; set; } public DateTimeOffset? EndDate { get; set; } public bool IsActive { get; set; } = true; public int Priority { get; set; } }
public sealed class Product { public Guid Id { get; set; } = Guid.NewGuid(); public string Name { get; set; } = null!; public string Slug { get; set; } = null!; public string? Description { get; set; } public decimal Price { get; set; } public string Currency { get; set; } = "TND"; public string? ImageUrl { get; set; } public string? Category { get; set; } public int Stock { get; set; } public bool IsActive { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class FanUser { public Guid Id { get; set; } = Guid.NewGuid(); public string Email { get; set; } = null!; public string DisplayName { get; set; } = null!; public string PasswordHash { get; set; } = null!; public bool IsActive { get; set; } = true; public bool EmailVerified { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset? LastLoginAt { get; set; } }
