import { useEffect, useState } from 'react'
import { adminApi } from '../api'
import { emptyNews } from '../constants'
export default function NewsModule({ onError }) {
  const [items,setItems]=useState([]); const [editing,setEditing]=useState(null); const [form,setForm]=useState(emptyNews)
  const [copiedId,setCopiedId]=useState(null); const [fbBusyId,setFbBusyId]=useState(null); const [notice,setNotice]=useState('')
  async function load(){try{setItems(await adminApi('/admin/news'))}catch(e){onError(e.message)}}
  useEffect(()=>{load()},[])
  function edit(item){setEditing(item.id);setForm({...item,publishedAt:item.publishedAt?.slice(0,16)||''})}
  async function save(e){e.preventDefault();try{const body={...form,publishedAt:form.publishedAt?new Date(form.publishedAt).toISOString():null};if(editing)await adminApi('/admin/news/'+editing,{method:'PUT',body:JSON.stringify(body)});else await adminApi('/admin/news',{method:'POST',body:JSON.stringify(body)});setEditing(null);setForm(emptyNews);await load()}catch(e){onError(e.message)}}
  async function publish(id){try{await adminApi('/admin/news/'+id+'/publish',{method:'POST'});await load()}catch(e){onError(e.message)}}
  async function unpublish(id){try{await adminApi('/admin/news/'+id+'/unpublish',{method:'POST'});await load()}catch(e){onError(e.message)}}
  async function remove(id){if(!confirm('Supprimer cet article ?'))return;try{await adminApi('/admin/news/'+id,{method:'DELETE'});if(editing===id){setEditing(null);setForm(emptyNews)}await load()}catch(e){onError(e.message)}}
  // Public shareable link for an article (opens the deep-link on the site).
  function publicUrl(slug){return window.location.origin+'/actualites/'+encodeURIComponent(slug)}
  async function copyLink(n){try{await navigator.clipboard.writeText(publicUrl(n.slug));setCopiedId(n.id);setTimeout(()=>setCopiedId(null),2000)}catch{onError('Impossible de copier le lien. Copiez-le depuis la barre d’adresse du site.')}}
  // Manual share: opens the Facebook sharer with the public link prefilled.
  function shareFacebook(n){window.open('https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(publicUrl(n.slug)),'_blank','noopener,noreferrer')}
  // Auto-post to the club's Facebook Page via the backend. If no Page token is
  // configured, the backend replies 400 with a clear message and we fall back
  // to the manual sharer so the editor is never blocked.
  async function publishToFacebook(n){setFbBusyId(n.id);setNotice('');try{const res=await adminApi('/admin/social/facebook/publish',{method:'POST',body:JSON.stringify({articleId:n.id})});setNotice(res?.message||'Publié sur Facebook.')}catch(e){onError(e.message+' — utilisez « Partager » pour publier manuellement.');shareFacebook(n)}finally{setFbBusyId(null)}}
  return <div className="grid gap-6 xl:grid-cols-[1fr_1.2fr]">
    <div className="rounded-[1.5rem] border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="text-xl font-black">News CMS</h2><button onClick={()=>{setEditing(null);setForm(emptyNews)}} className="rounded-xl bg-jso-navy p-2 text-white"><Plus size={18}/></button></div>{notice&&<p className="mt-3 rounded-xl bg-emerald-50 px-4 py-2 text-sm font-semibold text-emerald-700">{notice}</p>}<div className="mt-5 space-y-2">{items.map(n=><div key={n.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><b>{n.title}</b><p className="text-xs text-slate-500">{n.status} · {n.slug}</p></div><div className="flex gap-2">{n.status==='Published'?<button onClick={()=>unpublish(n.id)} title="Dépublier" className="text-amber-600"><EyeOff size={16}/></button>:<button onClick={()=>publish(n.id)} title="Publier" className="text-emerald-600"><Eye size={16}/></button>}<button onClick={()=>edit(n)} title="Modifier" className="text-jso-blue"><Pencil size={16}/></button><button onClick={()=>remove(n.id)} title="Supprimer" className="text-red-600"><X size={16}/></button></div></div>{n.status==='Published'&&<div className="mt-3 flex flex-wrap items-center gap-2 border-t border-slate-200 pt-3"><button onClick={()=>copyLink(n)} title="Copier le lien public" className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-jso-navy hover:border-jso-blue"><Link2 size={14}/>{copiedId===n.id?'Lien copié':'Copier le lien'}</button><button onClick={()=>shareFacebook(n)} title="Partager sur Facebook" className="inline-flex items-center gap-1.5 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs font-bold text-jso-navy hover:border-jso-blue"><Facebook size={14}/>Partager</button><button onClick={()=>publishToFacebook(n)} disabled={fbBusyId===n.id} title="Publier automatiquement sur la Page Facebook du club" className="inline-flex items-center gap-1.5 rounded-full bg-jso-navy px-3 py-1.5 text-xs font-bold text-white hover:bg-jso-blue disabled:opacity-50"><Send size={14}/>{fbBusyId===n.id?'Publication…':'Publier sur Facebook'}</button></div>}</div>)}</div></div>
    <form onSubmit={save} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 space-y-3"><h2 className="text-xl font-black">{editing?'Modifier l’article':'Nouvel article'}</h2><Field label="Titre" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><Field label="Slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} required/><Field label="Extrait" value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})}/><label className="block text-sm font-bold">Contenu<textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} rows="9" className="mt-2 w-full rounded-xl border border-slate-200 p-3 outline-none focus:border-jso-blue"/></label><Field label="Cover URL" value={form.coverImageUrl} onChange={e=>setForm({...form,coverImageUrl:e.target.value})}/><button className="flex items-center gap-2 rounded-xl bg-jso-navy px-4 py-2.5 font-bold text-white"><Save size={16}/>Enregistrer</button></form>
  </div>
}
