import { lazy } from 'react'

// Each section is loaded only when opened. The sidebar and dashboard remain
// available even when an individual module or its API is unavailable.
export const ADMIN_MODULES = {
  club: lazy(() => import('./club/ClubSettingsModule')),
  teams: lazy(() => import('./sport/TeamsModule')),
  matches: lazy(() => import('./sport/MatchesModule')),
  'seasons-competitions': lazy(() => import('./SeasonsCompetitions')),
  'match-events': lazy(() => import('./content/EventsModule')),
  formations: lazy(() => import('./sport/FormationsModule')),
  'match-sheet': lazy(() => import('./sport/MatchSheetModule')),
  news: lazy(() => import('./content/NewsModule')),
  security: lazy(() => import('./system/SecurityModule')),
  media: lazy(() => import('./content/MediaModule')),
  content: lazy(() => import('./content/ContentModule')),
  sponsors: lazy(() => import('./commerce/SponsorsModule')),
  sponsorqr: lazy(() => import('./SponsorQr')),
  shop: lazy(() => import('./commerce/ShopModule')),
  orders: lazy(() => import('./Orders')),
  tickets: lazy(() => import('./Tickets')),
  memberships: lazy(() => import('./Memberships')),
  'match-streams': lazy(() => import('./MatchStreams')),
  analytics: lazy(() => import('./sport/PlayerAnalyticsModule')),
  finance: lazy(() => import('./Finance')),
  donations: lazy(() => import('./Donations')),
  'cash-donations': lazy(() => import('./CashDonations')),
  volunteers: lazy(() => import('./Volunteers')),
  newsletter: lazy(() => import('./Newsletter')),
  archive: lazy(() => import('./Archive')),
  injuries: lazy(() => import('./Injuries')),
  supporters: lazy(() => import('./Supporters')),
  anniversaries: lazy(() => import('./Anniversaries')),
  editorial: lazy(() => import('./EditorialCalendar')),
  checklist: lazy(() => import('./Checklist')),
  classifieds: lazy(() => import('./Classifieds')),
  'fan-photos': lazy(() => import('./FanPhotos')),
  'community-moderation': lazy(() => import('./Community')),
  facilities: lazy(() => import('./Facilities')),
  scouting: lazy(() => import('./Scouting')),
  community: lazy(() => import('./CommunityPrograms')),
  featureflags: lazy(() => import('./FeatureFlags')),
  apiusage: lazy(() => import('./ApiUsage')),
  gdpr: lazy(() => import('./Gdpr')),
  'club-events': lazy(() => import('./ClubEvents')),
  documents: lazy(() => import('./Documents')),
  faq: lazy(() => import('./Faq')),
  settings: lazy(() => import('./system/SettingsModule')),
}
