import { lazy } from 'react'

// Each section is loaded only when opened. The sidebar and dashboard remain
// available even when an individual module or its API is unavailable.
export const ADMIN_MODULES = {
  club: lazy(() => import('./club/ClubSettingsModule')),
  teams: lazy(() => import('./sport/TeamsModule')),
  matches: lazy(() => import('./sport/MatchesModule')),
  'seasons-competitions': lazy(() => import('./sport/SeasonsCompetitions')),
  'match-events': lazy(() => import('./content/EventsModule')),
  formations: lazy(() => import('./sport/FormationsModule')),
  'match-sheet': lazy(() => import('./sport/MatchSheetModule')),
  news: lazy(() => import('./content/NewsModule')),
  security: lazy(() => import('./system/SecurityModule')),
  media: lazy(() => import('./content/MediaModule')),
  content: lazy(() => import('./content/ContentModule')),
  sponsors: lazy(() => import('./commerce/SponsorsModule')),
  sponsorqr: lazy(() => import('./commerce/SponsorQr')),
  shop: lazy(() => import('./commerce/ShopModule')),
  orders: lazy(() => import('./commerce/Orders')),
  tickets: lazy(() => import('./commerce/Tickets')),
  memberships: lazy(() => import('./commerce/Memberships')),
  'match-streams': lazy(() => import('./sport/MatchStreams')),
  analytics: lazy(() => import('./sport/PlayerAnalyticsModule')),
  finance: lazy(() => import('./commerce/Finance')),
  donations: lazy(() => import('./commerce/Donations')),
  'cash-donations': lazy(() => import('./commerce/CashDonations')),
  volunteers: lazy(() => import('./community/Volunteers')),
  newsletter: lazy(() => import('./community/Newsletter')),
  archive: lazy(() => import('./content/Archive')),
  injuries: lazy(() => import('./sport/Injuries')),
  supporters: lazy(() => import('./community/Supporters')),
  anniversaries: lazy(() => import('./community/Anniversaries')),
  editorial: lazy(() => import('./content/EditorialCalendar')),
  checklist: lazy(() => import('./sport/Checklist')),
  classifieds: lazy(() => import('./community/Classifieds')),
  'fan-photos': lazy(() => import('./community/FanPhotos')),
  'community-moderation': lazy(() => import('./community/Community')),
  facilities: lazy(() => import('./operations/Facilities')),
  scouting: lazy(() => import('./sport/Scouting')),
  community: lazy(() => import('./community/CommunityPrograms')),
  featureflags: lazy(() => import('./system/FeatureFlags')),
  apiusage: lazy(() => import('./system/ApiUsage')),
  gdpr: lazy(() => import('./system/Gdpr')),
  'club-events': lazy(() => import('./content/ClubEvents')),
  documents: lazy(() => import('./content/Documents')),
  faq: lazy(() => import('./content/Faq')),
  settings: lazy(() => import('./system/SettingsModule')),
}
