import { LayoutDashboard, Trophy, CreditCard, Wallet, HeartHandshake, ShoppingBag, Receipt, Handshake, QrCode, Users, CalendarDays, Radio, BarChart3, HeartPulse, ScanSearch, ListChecks, Newspaper, CalendarClock, Images, Pencil, PartyPopper, FileText, HelpCircle, MessageSquare, BrickWall, Megaphone, Mail, ClipboardList, GraduationCap, CalendarRange, ShieldCheck, Flag, Gauge, ShieldAlert, Server, Ticket, Landmark, Banknote } from 'lucide-react'
export const ADMIN_NAVIGATION = [
    ['dashboard', 'Dashboard', LayoutDashboard, ['SuperAdmin','ClubAdmin','Editor','MatchManager','CommunityManager','ShopManager'], 'Tableau de bord'],

    ['tickets', 'Billetterie', Ticket, ['SuperAdmin','ClubAdmin','MatchManager','TicketSeller','TicketSupervisor'], 'Billetterie & Abonnements'],
    ['memberships', 'Abonnements', CreditCard, ['SuperAdmin','ClubAdmin','SeasonManager'], 'Billetterie & Abonnements'],
    ['finance', 'Finances', Wallet, ['SuperAdmin','ClubAdmin','FinanceManager'], 'Finances & dons'],
    ['donations', 'Dons & collecte', HeartHandshake, ['SuperAdmin','ClubAdmin','FinanceManager'], 'Finances & dons'],
    ['cash-donations', 'Dons en espèces', Banknote, ['SuperAdmin','ClubAdmin','FinanceManager','ShopManager','TicketSeller','TicketSupervisor'], 'Finances & dons'],

    ['shop', 'Boutique', ShoppingBag, ['SuperAdmin','ClubAdmin','ShopManager'], 'Boutique & partenaires'],
    ['orders', 'Commandes', Receipt, ['SuperAdmin','ClubAdmin','ShopManager'], 'Boutique & partenaires'],
    ['sponsors', 'Sponsors', Handshake, ['SuperAdmin','ClubAdmin'], 'Boutique & partenaires'],
    ['sponsorqr', 'QR Sponsors', QrCode, ['SuperAdmin','ClubAdmin'], 'Boutique & partenaires'],

    ['matches', 'Match Center', Trophy, ['SuperAdmin','ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['match-events', 'Événements de match', Trophy, ['SuperAdmin','ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['match-sheet', 'Feuille de match', ClipboardList, ['SuperAdmin','ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['formations', 'Formations', Users, ['SuperAdmin','ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['teams', 'Équipes & joueurs', Users, ['SuperAdmin','ClubAdmin'], 'Équipe & Matchs'],
    ['seasons-competitions', 'Saisons & compétitions', CalendarDays, ['SuperAdmin','ClubAdmin'], 'Équipe & Matchs'],
    ['match-streams', 'Diffusion en direct', Radio, ['ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['analytics', 'Analytics joueurs', BarChart3, ['SuperAdmin','ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['injuries', 'Infirmerie', HeartPulse, ['ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['scouting', 'Scouting', ScanSearch, ['ClubAdmin','MatchManager'], 'Équipe & Matchs'],
    ['checklist', 'Check-list match', ListChecks, ['ClubAdmin','MatchManager'], 'Équipe & Matchs'],

    ['news', 'News CMS', Newspaper, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['editorial', 'Calendrier éditorial', CalendarClock, ['Editor','ClubAdmin'], 'Contenu & Site'],
    ['media', 'Médias', Images, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['content', 'Contenus', Pencil, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['club-events', 'Agenda du club', PartyPopper, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['documents', 'Documents', FileText, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['faq', 'FAQ', HelpCircle, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],
    ['archive', 'Musée · Archives', Landmark, ['SuperAdmin','ClubAdmin','Editor'], 'Contenu & Site'],

    ['community-moderation', 'Communauté · Modération', MessageSquare, ['ClubAdmin','CommunityManager'], 'Communauté'],
    ['fan-photos', 'Photos supporters', Images, ['CommunityManager','Editor'], 'Communauté'],
    ['supporters', 'Mur des supporters', BrickWall, ['ClubAdmin','CommunityManager'], 'Communauté'],
    ['classifieds', 'Petites annonces', Megaphone, ['ClubAdmin','CommunityManager'], 'Communauté'],
    ['anniversaries', 'Anniversaires', PartyPopper, ['ClubAdmin','CommunityManager'], 'Communauté'],
    ['newsletter', 'Newsletter', Mail, ['Editor','CommunityManager'], 'Communauté'],
    ['volunteers', 'Bénévoles', ClipboardList, ['ClubAdmin','MatchManager'], 'Communauté'],
    ['community', 'Écoles & partenaires', GraduationCap, ['ClubAdmin','CommunityManager'], 'Communauté'],
    ['facilities', 'Installations', CalendarRange, ['ClubAdmin','MatchManager'], 'Communauté'],

    ['club', 'Club Settings', ShieldCheck, ['SuperAdmin','ClubAdmin'], 'Système'],
    ['security', 'Sécurité', ShieldCheck, ['SuperAdmin'], 'Système'],
    ['featureflags', 'Feature flags', Flag, ['SuperAdmin','ClubAdmin'], 'Système'],
    ['apiusage', 'Utilisation API', Gauge, ['SuperAdmin','ClubAdmin'], 'Système'],
    ['gdpr', 'RGPD', ShieldAlert, ['SuperAdmin','ClubAdmin'], 'Système'],
    ['settings', 'Configuration', Server, ['SuperAdmin','ClubAdmin'], 'Système'],
]
export const ADMIN_PERMISSION_BY_ID = Object.freeze({
  dashboard: 'dashboard:view',
  tickets: 'tickets:admin',
  memberships: 'memberships:manage',
  finance: 'finance:view',
  donations: 'finance:view',
  'cash-donations': 'donations:cash',
  shop: 'shop:manage',
  orders: 'orders:manage',
  sponsors: 'sponsors:manage',
  sponsorqr: 'sponsors:qr',
  matches: 'matches:manage',
  'match-events': 'matches:events',
  'match-sheet': 'matches:sheet',
  formations: 'matches:formations',
  teams: 'teams:manage',
  'seasons-competitions': 'competitions:manage',
  'match-streams': 'matches:stream',
  analytics: 'analytics:view',
  injuries: 'medical:manage',
  scouting: 'scouting:manage',
  checklist: 'matches:checklist',
  news: 'content:news',
  editorial: 'content:calendar',
  media: 'content:media',
  content: 'content:manage',
  'club-events': 'content:events',
  documents: 'content:documents',
  faq: 'content:faq',
  archive: 'content:archive',
  'community-moderation': 'community:moderate',
  'fan-photos': 'community:photos',
  supporters: 'community:supporters',
  classifieds: 'community:classifieds',
  anniversaries: 'community:anniversaries',
  newsletter: 'community:newsletter',
  volunteers: 'community:volunteers',
  community: 'community:programs',
  facilities: 'facilities:manage',
  club: 'club:manage',
  security: 'security:manage',
  featureflags: 'system:feature-flags',
  apiusage: 'system:api-usage',
  gdpr: 'system:gdpr',
  settings: 'system:settings',
})
export const ADMIN_CATEGORY_ORDER = ['Tableau de bord', 'Billetterie & Abonnements', 'Finances & dons', 'Boutique & partenaires', 'Équipe & Matchs', 'Contenu & Site', 'Communauté', 'Système']

export const ADMIN_PUBLIC_PATHS = Object.freeze({
  tickets: '/billetterie',
  memberships: '/abonnements',
  donations: '/soutenir',
  'cash-donations': '/soutenir',
  shop: '/boutique',
  orders: '/boutique',
  sponsors: '/partenaires',
  sponsorqr: '/partenaires',
  matches: '/matchs',
  'match-events': '/matchs',
  teams: '/equipe',
  news: '/actualites',
  media: '/medias',
  'club-events': '/agenda',
  archive: '/musee',
  supporters: '/communaute',
  community: '/communaute',
  club: '/club',
})

export function visibleAdminItems(role, query = '') {
  const search = query.trim().toLocaleLowerCase('fr')
  return ADMIN_NAVIGATION.filter(([id, label, , roles, category]) =>
    roles.includes(role) && Boolean(ADMIN_PERMISSION_BY_ID[id]) &&
    (!search || `${label} ${category} ${id}`.toLocaleLowerCase('fr').includes(search)))
}
